<!--nav start-->
	<input type="checkbox" id="nav-trigger" class="nav-trigger" />
	<label for="nav-trigger"></label>
	<ul class="navigation">
	    <li class="nav-item"><a href="#">tools &amp; standards</a></li>
	    <li class="nav-item"><a href="#">html5</a></li>
	    <li class="nav-item"><a href="#">css techniques</a></li>
	    <li class="nav-item"><a href="#">css layouts</a></li>
	    <li class="nav-item"><a href="#">responsive css</a></li>
	    <li class="nav-item"><a href="#">css3</a></li>
	    <li class="nav-item"><a href="#">javascript frameworks</a></li>
	    <li class="nav-item"><a href="#">dynamic content</a></li>
		<li class="nav-item"><a href="#">templating &amp; seo</a></li>
		<li class="nav-item"><a href="#">methodology</a></li>
		<li class="nav-item"><a href="#">project work</a></li>
	</ul>
<!--nav end-->
