<!--nav start-->
	<input type="checkbox" id="nav-trigger" class="nav-trigger" />
	<label for="nav-trigger"></label>
	<ul class="navigation">
	    <li class="nav-item"><a href="#">Tools &amp; Standards</a></li>
	    <li class="nav-item"><a href="#">HTML5</a></li>
	    <li class="nav-item"><a href="#">CSS Techniques</a></li>
	    <li class="nav-item"><a href="#">CSS Layouts</a></li>
	    <li class="nav-item"><a href="#">Responsive CSS</a></li>
	    <li class="nav-item"><a href="#">CSS3</a></li>
	    <li class="nav-item"><a href="#">JavaScript Frameworks</a></li>
	    <li class="nav-item"><a href="#">Dynamic Content</a></li>
		<li class="nav-item"><a href="#">Templating &amp; seo</a></li>
		<li class="nav-item"><a href="#">Methodology</a></li>
		<li class="nav-item"><a href="#">Project Work</a></li>
	</ul>
<!--nav end-->
