<section id="rightcont">

	<h3 class="navhead">contents</h3>


	<a href="/1950/">home</a>
	<span class="none"> | </span>


	<a href="/1950/courseinfo/">about the course</a>
	<span class="none"> | </span>



	<a href="/1950/resources/">resources</a>
	<span class="none"> | </span>


	<!--
****************************************************************
<a href="/1950/lectures/three"> </a>

<span class="greyout">
****************************************************************
-->
	<h3 class="navhead">lectures</h3>

	<a href="/1950/lectures/">01 | tools &amp; standards</a> <span class="none"> | </span>

	<a href="/1950/lectures/two/">02 | html5</a> <span class="none"> | </span>



	<a href="/1950/lectures/three/">03 | css techniques</a> <span class="none"> | </span>


	<a href="/1950/lectures/four/">04 | css layouts</a>
	<span class="none"> | </span>

	<a href="/1950/lectures/five/">05 | responsive css</a>
	<span class="none"> | </span>

	<a href="/1950/lectures/six/">06 | css3</a>
	<span class="none"> | </span>

	<a href="/1950/lectures/seven/">07 | javascript frameworks</a> <span class="none"> | </span>

	<a href="/1950/lectures/eight/">08 | dynamic content</a> <span class="none"> | </span>

	<a href="/1950/lectures/nine/">09 | templating, seo</a> <span class="none"> | </span>

	<span class="navoff">10 | methodology</span>
	<span class="none"> | </span>

	<a href="/1950/lectures/eleven/">11 | project work</a> <span class="none"> | </span>

	<h3 class="navhead">contact</h3>

	<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#106;&#101;&#102;&#102;&#114;&#101;&#121;&#95;&#112;&#97;&#114;&#107;&#101;&#114;&#64;&#98;&#99;&#105;&#116;&#46;&#99;&#97;">jeff parker</a>
	<span class="none"> | </span>


	<h3 class="navhead">associated</h3>

	<a href="http://bcitcomp.ca/students/">students on bcitcomp.ca</a>
	<span class="none"> | </span>

	<a href="http://my.bcit.ca/">my.bcit</a>
	<span class="none"> | </span>

	<a href="http://www.bcit.ca/">bcit</a>
	<span class="none"> | </span>

	<a href="http://www.bcit.ca/cas/computing/">bcit: computing</a>
	<span class="none"> | </span>

</section>
